config/routes.rb
Rails.application.routes.draw do
  resources :searches
  resources :articles
  devise_for :users
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root 'articles#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/article.rb
class Article < ApplicationRecord
  include PgSearch::Model
  belongs_to :user

  pg_search_scope :search, against: { title: 'A', content: 'C' }, using: { tsearch: { prefix: true } }

  validates :title, presence: true, length: { in: 1..100 }
  validates :content, presence: true, length: { in: 1..500 }
end

app/models/search.rb
class Search < ApplicationRecord
  belongs_to :user

  validates :query, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :searches, dependent: :destroy
  has_many :articles, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: %i[first_name last_name address phone date_of_birth gender])
    devise_parameter_sanitizer.permit(:account_update,
                                      keys: %i[first_name last_name address phone date_of_birth gender])
  end
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  include SearchesHelper
  before_action :set_query, only: %i[index]

  def index
    if @query.present?
      @articles = Article.search(@query).includes(:user)

      update_or_create_search(@query, current_user) if search_valid?(@query)
    else
      @articles = Article.all.includes(:user)
    end
  end

  private

  def set_query
    @query = params[:query]
  end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  include SearchesHelper

  before_action :set_api_key, only: %i[index]

  def index
    @user_searches = current_user.searches.where(confirm: false)
    @searches = Search.all.includes(:user).where(user_id: current_user.id, confirm: true).order(count: :desc).limit(10)

    if @user_searches.present?
      queries = convert_queries_to_string(@user_searches)

      ids = filter_valid_queries_ids(queries, @api_key)

      @user_searches.where(id: ids).update_all(confirm: true) if ids.any?
      @user_searches.where.not(id: ids).delete_all
    else
      @searches
    end
  end

  private

  def set_api_key
    @api_key = Rails.application.credentials.production[:open_ai][:api_key]
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/searches_helper.rb
require "faraday"

module SearchesHelper
  def search_valid?(input)
    words = input.strip.split

    # Questions must be at least 3 words long because of the structure of a question in English language
    return false unless words.length >= 3

    # Only save searches where the first word is at least 2 characters long for questions(Is it, Do you) and last word is at least 2 characters long so that questions doesn't end with single character
    words[-1].length >= 2 && words[0].length >= 2
  end

  def update_or_create_search(query, user)
    existing_search = Search.find_by(query: query.strip.downcase, user_id: user.id)

    if existing_search
      existing_search.update(count: existing_search.count + 1)
    else
      Search.create(query: query.strip.downcase, user:)
    end
  end

  def convert_queries_to_string(queries)
    queries.pluck(:query, :id).map { |s| "'{#{s[0]}},#{s[1]}'" }.join(",")
  end

  def filter_valid_queries_ids(queries, api_key)
    connection = Faraday.new(url: "https://api.openai.com/v1/chat/completions")

    res = connection.post do |req|
      req.headers["Content-Type"] = "application/json"
      req.headers["Authorization"] = "Bearer #{api_key}"
      req.body = {
        model: "gpt-3.5-turbo",
        messages: [
          {
            role: "system",
            content: "You're a grammar checker. I'll send you the inputs with their number in this format '{input},number' separated by commas. Your task is to filter everything that are not questions.If you can't read the sentence or words, simply ignore them. Send me the number of the grammatically correct questions that have objects by separating them by commas. If there is none, simply send back a empty space.",
          },
          {
            role: "user",
            content: queries.to_s,
          },
        ],
        temperature: 0.7,
      }.to_json
    end

    response = JSON.parse(res.body)
    response["choices"][0]["message"]["content"].split(",")
  end
end

app/views/articles/_article.html.erb
<div id="<%= dom_id article %>" class="card_container">
  <p class="card_title">
    "<%= article.title %>" by <%= article.user.name %>
  </p>
  <p>
    <%= article.content %>
  </p>
</div>

app/views/articles/index.html.erb
<main class="main_container">
  <h1 class="main_title"><%= pluralize(@articles.length, "article") %></h1>
  <%= form_with(url: articles_path, method: :get, data: { controller: "search-input" }, class: "search_bar_container") do |form| %>
    <%= form.text_field :query, placeholder: "Search articles...", data: {
                                  action: "input->search-input#search",
                                }, id: "search_input" %>
    <span>
      <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" viewBox="0 0 1024 1024"><path fill="#6b1aef" d="M1014.64 969.04L703.71 656.207c57.952-69.408 92.88-158.704 92.88-256.208c0-220.912-179.088-400-400-400s-400 179.088-400 400s179.088 400 400 400c100.368 0 192.048-37.056 262.288-98.144l310.496 312.448c12.496 12.497 32.769 12.497 45.265 0c12.48-12.496 12.48-32.752 0-45.263zM396.59 736.527c-185.856 0-336.528-150.672-336.528-336.528S210.734 63.471 396.59 63.471c185.856 0 336.528 150.672 336.528 336.528S582.446 736.527 396.59 736.527"/></svg>
    </span>
  <% end %>
  <% @articles.each do |article| %>
    <%= render article %>
  <% end %>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Search Analytics Engine</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <link rel="icon" href="<%= asset_path('seo.png') %>" type="image/png" />
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <p style="color: green; text-align: center;"><%= notice %></p>
    <p style="color: red; text-align: center;"><%= alert %></p>
    <%= render "shared/navbar" %>
    <%= yield %>
  </body>
</html>

app/views/searches/_search.html.erb
<div id="<%= dom_id search %>" class="card_container"
>
  <span class="card_title">
    <span>
      "<%= search.query.capitalize %>"
    </span>
    <span>for</span>
    <%= pluralize(search.count, "time") %>
  </span>
</div>

app/views/searches/index.html.erb
<main class="main_container">
  <h1 class="main_title"><%= pluralize(@searches.length, "popular search") %></h1>
  <div id="searches">
    <% @searches.each do |search| %>
      <%= render search %>
    <% end %>
  </div>
</main>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
  <div class="nav_container">
    <div class="links_container">
      <%= link_to "Articles", articles_path %>
      <%= link_to "Analytics", searches_path %>
    </div>
    <%= button_to "Log out", destroy_user_session_path, method: "delete", id: "log_out_btn" %>
  </div>
<% end %>